apps/admn_caja/urls.py
from django.conf.urls import url 
#views.
from .views.v_tipo_movimiento import list_tipo_movimiento,add_tipo_movimiento,update_tipo_movimiento,deletetipo_movimiento
from .views.v_tipo_pago import list_tipo_pago,add_tipo_pago,update_tipo_pago,deletetipo_pago
from .views.v_comprobante import list_comprobante,add_comprobante,update_comprobante,deletecomprobante
from .views.v_cajas import list_cajas,add_cajas,update_cajas,deletecajas,listasesiones,aperturar,cerrar
from .views.v_conceptos import list_conceptos,add_conceptos,update_conceptos,deleteconceptos
from .views.v_movimientos import *
#.

urlpatterns = [
  # tipo_movimiento
  url(r'^admn_caja/tipo_movimiento/listar/$', list_tipo_movimiento.as_view()),
  url(r'^admn_caja/tipo_movimiento/add/$', add_tipo_movimiento.as_view()),
  url(r'^admn_caja/tipo_movimiento/update/(?P<pk>\d+)/$', update_tipo_movimiento.as_view()),
  url(r'^admn_caja/tipo_movimiento/delete/(?P<id>\d+)/$', deletetipo_movimiento),


  # tipo_pago
  url(r'^admn_caja/tipo_pago/listar/$', list_tipo_pago.as_view()),
  url(r'^admn_caja/tipo_pago/add/$', add_tipo_pago.as_view()),
  url(r'^admn_caja/tipo_pago/update/(?P<pk>\d+)/$', update_tipo_pago.as_view()),
  url(r'^admn_caja/tipo_pago/delete/(?P<id>\d+)/$', deletetipo_pago),


  # comprobante
  url(r'^admn_caja/comprobante/listar/$', list_comprobante.as_view()),
  url(r'^admn_caja/comprobante/add/$', add_comprobante.as_view()),
  url(r'^admn_caja/comprobante/update/(?P<pk>\d+)/$', update_comprobante.as_view()),
  url(r'^admn_caja/comprobante/delete/(?P<id>\d+)/$', deletecomprobante),


  # cajas
  url(r'^admn_caja/cajas/listar/$', list_cajas.as_view()),
  url(r'^admn_caja/cajas/add/$', add_cajas.as_view()),
  url(r'^admn_caja/cajas/update/(?P<pk>\d+)/$', update_cajas.as_view()),
  url(r'^admn_caja/cajas/delete/(?P<id>\d+)/$', deletecajas),

  # sesiones cajas
  url(r'^admn_caja/sesion_caja/listar/$', listasesiones),
  url(r'^admn_caja/sesion_caja/aperturar/$', aperturar),
  url(r'^admn_caja/sesion_caja/cerrar/$', cerrar),

  # conceptos
  url(r'^admn_caja/conceptos/listar/$', list_conceptos.as_view()),
  url(r'^admn_caja/conceptos/add/$', add_conceptos.as_view()),
  url(r'^admn_caja/conceptos/update/(?P<pk>\d+)/$', update_conceptos.as_view()),
  url(r'^admn_caja/conceptos/delete/(?P<id>\d+)/$', deleteconceptos),

  # movimientos
  url(r'^admn_caja/movimientos/listar/$', movimientos_hoy),
  url(r'^admn_caja/movimientos/historial/$', movimientos_historial),
  url(r'^admn_caja/movimientos/validarcaja/$', validarcaja),
  url(r'^admn_caja/movimientos/add/$', add_movimiento),
  url(r'^admn_caja/movimientos/extornarmovi/$', extornarmovi),
  url(r'^admn_caja/movimientos/conceptos_tipo/$', conceptos_tipo),
  url(r'^admn_caja/movimientos/guardarmovimiento/$', guardarmovimiento),
]

config/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.security.urls')),
    url(r'^', include('apps.admn_caja.urls')),
  url(r'^', include('apps.reportes.urls')),
  url(r'^', include('apps.servicio.urls')),
  url(r'^', include('apps.compra.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/admn_caja/models.py
from django.db import models
from apps.core.core import TimeStampedModel

# Create your models here.
class tipo_movimiento(TimeStampedModel):
    descripcion = models.CharField(max_length=100)

    def __str__(self):
        return self.descripcion

    def l_tipo_mo(self):
       return tipo_movimiento.objects.filter(status=True)

class tipo_pago(TimeStampedModel):
    descripcion = models.CharField(max_length=100)

    def __str__(self):
        return self.descripcion

    def l_tipo_pa(self):
       return tipo_pago.objects.filter(status=True)

class comprobante(TimeStampedModel):
    descripcion = models.CharField(max_length=100)
    correlativo_inicial = models.CharField(max_length=100,default='0000001')
    correlativo = models.CharField(max_length=100)

    def __str__(self):
        return self.descripcion

    def l_comprobante(self):
       return comprobante.objects.filter(status=True)

class cajas(TimeStampedModel):
    descripcion = models.CharField(max_length=100)
    montoingresos = models.FloatField(default=0.00)
    montoegresos = models.FloatField(default=0.00)
    montototal = models.FloatField(default=0.00)

    def __str__(self):
        return self.descripcion

    def l_cajas(self):
       return cajas.objects.filter(status=True)

class conceptos(TimeStampedModel):
    descripcion = models.CharField(max_length=100)
    idtipo_movimiento = models.ForeignKey(tipo_movimiento)

    def __str__(self):
        return self.descripcion

    def l_conceptos(self):
       return conceptos.objects.filter(status=True)

class sesion_caja(TimeStampedModel):
    idcaja = models.ForeignKey('cajas')
    idusuario = models.ForeignKey('security.Users')
    fecha = models.DateField()
    montoapertura = models.FloatField()
    montocierre = models.FloatField()

    def __str__(self):
        return self.fecha

class movimiento(TimeStampedModel):
    idconcepto     = models.ForeignKey('conceptos')
    idcomprobante  = models.ForeignKey('comprobante')
    idsesioncaja   = models.ForeignKey('sesion_caja')
    nrocomprobante = models.CharField(max_length=100)
    descripcion  = models.CharField(max_length=100)
    fecha        = models.DateField()
    monto        = models.FloatField()

    def __str__(self):
        return self.monto

    def l_movimiento(self):
       return movimiento.objects.filter(status=True)

apps/admn_caja/forms/f_cajas.py
from django import forms
from ..models import cajas

class cajasForm(forms.ModelForm):
  class Meta():
    model = cajas
    fields = '__all__'
    exclude = ('status', 'deleted_at')

apps/admn_caja/forms/f_comprobante.py
from django import forms
from ..models import comprobante

class comprobanteForm(forms.ModelForm):
  class Meta():
    model = comprobante
    fields = '__all__'
    exclude = ('status', 'deleted_at')

apps/admn_caja/forms/f_conceptos.py
from django import forms
from ..models import conceptos

class conceptosForm(forms.ModelForm):
  class Meta():
    model = conceptos
    fields = '__all__'
    exclude = ('status', 'deleted_at')

apps/admn_caja/forms/f_tipo_movimiento.py
from django import forms
from ..models import tipo_movimiento

class tipo_movimientoForm(forms.ModelForm):
  class Meta():
    model = tipo_movimiento
    fields = '__all__'
    exclude = ('status', 'deleted_at')

apps/admn_caja/forms/f_tipo_pago.py
from django import forms
from ..models import tipo_pago

class tipo_pagoForm(forms.ModelForm):
  class Meta():
    model = tipo_pago
    fields = '__all__'
    exclude = ('status', 'deleted_at')

apps/admn_caja/views/v_cajas.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,HttpResponse
from apps.core.crud import ListBase, SaveBase, UpdateBase
from ..models import cajas,sesion_caja
from ..forms.f_cajas import cajasForm

from django.db.models import Max,Count
from datetime import datetime

today  = datetime.now()
date   = today.strftime("%Y-%m-%d")

class list_cajas(ListBase):
  template_name = 'cajas/list_cajas.html'
  queryset = cajas.objects.filter(status=True).values()

class add_cajas(SaveBase):
  form_class = cajasForm
  template_name = 'cajas/frm_cajas.html'

class update_cajas(UpdateBase):
  form_class = cajasForm
  template_name = 'cajas/frm_cajas.html'
  model = cajas

@login_required(login_url='login/')
def deletecajas(em, id):
  dp = cajas.objects.get(pk=id)
  dp.status = False
  dp.save()
  return HttpResponse('DATOS ELIMINADOS')

@login_required(login_url='login/')
def listasesiones(request):
  listacajas = cajas.objects.filter(status=True)
  lista = sesion_caja.objects.filter(idusuario_id=request.user.id).order_by("-id")
  cajaestado = sesion_caja.objects.filter(idusuario_id=request.user.id,status=True)
  caja_estado = 'false'
  for obj in cajaestado:
    caja_estado = 'true'

  data = {'listasesiones': lista,'listacajas':listacajas, 'caja_estado': caja_estado}
  return render(request, 'cajas/sesiones.html', data)


def aperturar(request):
  if request.is_ajax():
    montoapertura = 0
    sesionid = sesion_caja.objects.all().aggregate(Max('id'))
    sesionid = sesionid['id__max']
    sesiones = sesion_caja.objects.filter(id=sesionid)
    for obj in sesiones:
      montoapertura = obj.montocierre

    apertura = sesion_caja()
    apertura.created_at = date
    apertura.updated_at = date
    apertura.fecha = date
    apertura.status = True
    apertura.montoapertura = montoapertura
    apertura.montocierre = 0.00
    apertura.idcaja_id = request.GET["caja"]
    apertura.idusuario_id = request.user.id
    apertura.save()
    return HttpResponse('true')


def cerrar(request):
  if request.is_ajax():
    cajaestado = sesion_caja.objects.filter(idusuario_id=request.user.id,status=True)
    for obj in cajaestado:
      idsesion = obj.id
      idcajaactual = obj.idcaja_id

    cajainfo = cajas.objects.filter(id=int(idcajaactual))
    for caj in cajainfo:
      saldocierre = caj.montototal

    cierre = sesion_caja.objects.get(id=int(idsesion))
    cierre.montocierre = saldocierre
    cierre.status = False
    cierre.save()
    return HttpResponse('true')

apps/admn_caja/views/v_comprobante.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import HttpResponse
from apps.core.crud import ListBase, SaveBase, UpdateBase
from ..models import comprobante
from ..forms.f_comprobante import comprobanteForm

class list_comprobante(ListBase):
  template_name = 'comprobante/list_comprobante.html'
  queryset = comprobante.objects.filter(status=True).values()

class add_comprobante(SaveBase):
  form_class = comprobanteForm
  template_name = 'comprobante/frm_comprobante.html'

class update_comprobante(UpdateBase):
  form_class = comprobanteForm
  template_name = 'comprobante/frm_comprobante.html'
  model = comprobante

@login_required(login_url='login/')
def deletecomprobante(em, id):
  dp = comprobante.objects.get(pk=id)
  dp.status = False
  dp.save()
  return HttpResponse('DATOS ELIMINADOS') 

apps/admn_caja/views/v_conceptos.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import HttpResponse
from apps.core.crud import ListBase, SaveBase, UpdateBase
from ..models import conceptos
from ..forms.f_conceptos import conceptosForm

class list_conceptos(ListBase):
  template_name = 'conceptos/list_conceptos.html'
  queryset = conceptos.objects.filter(status=True).values()

class add_conceptos(SaveBase):
  form_class = conceptosForm
  template_name = 'conceptos/frm_conceptos.html'

class update_conceptos(UpdateBase):
  form_class = conceptosForm
  template_name = 'conceptos/frm_conceptos.html'
  model = conceptos

@login_required(login_url='login/')
def deleteconceptos(em, id):
  dp = conceptos.objects.get(pk=id)
  dp.status = False
  dp.save()
  return HttpResponse('DATOS ELIMINADOS') 

apps/admn_caja/views/v_movimientos.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,HttpResponse
from ..models import cajas,sesion_caja,movimiento,comprobante,conceptos

from django.db.models import Max,Count
from datetime import datetime

today  = datetime.now()
date   = today.strftime("%Y-%m-%d")

@login_required(login_url='login/')
def movimientos_hoy(request):
  listamovimientos = movimiento.objects.filter(fecha=date,status=True).order_by('-id')
  data = {'listamovimientos': listamovimientos}
  return render(request, 'movimientos/movimientos_hoy.html', data)

@login_required(login_url='login/')
def movimientos_historial(request):
  listamovimientos = movimiento.objects.filter(status=True).order_by('-id')
  data = {'listamovimientos': listamovimientos}
  return render(request, 'movimientos/movimientos_historial.html', data)

@login_required(login_url='login/')
def add_movimiento(request):
    comprobanteslista = comprobante.objects.filter(status=True)
    data = {'comprobanteslista':comprobanteslista}
    return render(request, 'movimientos/nuevo.html', data)

@login_required(login_url='login/')
def extornarmovi(request):
    if request.is_ajax():
        cajaaperturada = sesion_caja.objects.filter(idusuario_id=request.user.id, status=True)
        for obj in cajaaperturada:
            cajainfo = cajas.objects.filter(id=int(obj.idcaja_id))
            for caj in cajainfo:
                saldoingresos = caj.montoingresos
                saldoegresos = caj.montoegresos
                saldototal = caj.montototal

            if (int(request.GET['tipomovimiento']) == 1):
                saldoingresos = float(saldoingresos) - float(request.GET['monto'])
                saldoegresos = float(saldoegresos)
                saldototal = float(saldototal) - float(request.GET['monto'])
            else:
                saldoingresos = float(saldoingresos)
                saldoegresos = float(saldoegresos) - float(request.GET['monto'])
                saldototal = float(saldototal) + float(request.GET['monto'])

            upcajas = cajas.objects.get(id=int(obj.idcaja_id))
            upcajas.montoingresos = saldoingresos
            upcajas.montoegresos = saldoegresos
            upcajas.montototal = saldototal
            upcajas.save()

            movi = movimiento.objects.get(id=int(request.GET['id']))
            movi.status = False
            movi.save()

            return HttpResponse('true')

def validarcaja(request):
    if request.is_ajax():
        cajaaperturada = sesion_caja.objects.filter(idusuario_id=request.user.id,status=True)
        info = "aperturar"
        for obj in cajaaperturada:
            cajainfo = cajas.objects.filter(id=obj.idcaja_id)
            for ob in cajainfo:
                if str(obj.fecha) == str(date):
                    info = "aperturada"
                else:
                    info = "aperturarfecha"

        return HttpResponse(info)

def conceptos_tipo(request):
    if request.is_ajax():
        lisconceptos = conceptos.objects.filter(idtipo_movimiento_id=request.GET['id'])
        html = "<option value=''>Seleccione</option>"
        for obj in lisconceptos:
            html += "<option value='" + str(obj.id) + "'>" + obj.descripcion + "</option>"

        return HttpResponse(html)


def guardarmovimiento(request):
    if request.is_ajax():
        cajaaperturada = sesion_caja.objects.filter(idusuario_id=request.user.id,status=True)
        for obj in cajaaperturada:
            cajainfo = cajas.objects.filter(id=int(obj.idcaja_id))
            for caj in cajainfo:
                saldoingresos = caj.montoingresos
                saldoegresos = caj.montoegresos
                saldototal = caj.montototal

            if (int(request.GET['tipomovimiento']) == 1):
                saldoingresos = float(saldoingresos) + float(request.GET['monto'])
                saldoegresos = float(saldoegresos)
                saldototal = float(saldototal) + float(request.GET['monto'])
            else:
                saldoingresos = float(saldoingresos)
                saldoegresos = float(saldoegresos) + float(request.GET['monto'])
                saldototal = float(saldototal) - float(request.GET['monto'])

            upcajas = cajas.objects.get(id=int(obj.idcaja_id))
            upcajas.montoingresos = saldoingresos
            upcajas.montoegresos = saldoegresos
            upcajas.montototal = saldototal
            upcajas.save()

            n_movi = movimiento()
            n_movi.created_at = date
            n_movi.updated_at = date
            n_movi.descripcion = request.GET['descripcion']
            n_movi.fecha = date
            n_movi.monto = request.GET['monto']
            n_movi.nrocomprobante = request.GET['nrocomprobante']
            n_movi.idcomprobante_id = int(request.GET['comprobante'])
            n_movi.idconcepto_id = int(request.GET['concepto'])
            n_movi.idsesioncaja_id = obj.id
            n_movi.save()

        return HttpResponse("true")

apps/admn_caja/views/v_tipo_movimiento.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import HttpResponse
from apps.core.crud import ListBase, SaveBase, UpdateBase
from ..models import tipo_movimiento
from ..forms.f_tipo_movimiento import tipo_movimientoForm

class list_tipo_movimiento(ListBase):
  template_name = 'tipo_movimiento/list_tipo_movimiento.html'
  queryset = tipo_movimiento.objects.filter(status=True).values()

class add_tipo_movimiento(SaveBase):
  form_class = tipo_movimientoForm
  template_name = 'tipo_movimiento/frm_tipo_movimiento.html'

class update_tipo_movimiento(UpdateBase):
  form_class = tipo_movimientoForm
  template_name = 'tipo_movimiento/frm_tipo_movimiento.html'
  model = tipo_movimiento

@login_required(login_url='login/')
def deletetipo_movimiento(em, id):
  dp = tipo_movimiento.objects.get(pk=id)
  dp.status = False
  dp.save()
  return HttpResponse('DATOS ELIMINADOS') 

apps/admn_caja/views/v_tipo_pago.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import HttpResponse
from apps.core.crud import ListBase, SaveBase, UpdateBase
from ..models import tipo_pago
from ..forms.f_tipo_pago import tipo_pagoForm

class list_tipo_pago(ListBase):
  template_name = 'tipo_pago/list_tipo_pago.html'
  queryset = tipo_pago.objects.filter(status=True).values()

class add_tipo_pago(SaveBase):
  form_class = tipo_pagoForm
  template_name = 'tipo_pago/frm_tipo_pago.html'

class update_tipo_pago(UpdateBase):
  form_class = tipo_pagoForm
  template_name = 'tipo_pago/frm_tipo_pago.html'
  model = tipo_pago

@login_required(login_url='login/')
def deletetipo_pago(em, id):
  dp = tipo_pago.objects.get(pk=id)
  dp.status = False
  dp.save()
  return HttpResponse('DATOS ELIMINADOS') 

apps/admn_caja/templates/cajas/frm_cajas.html
<div class="card-panel">
    <a class="waves-effect waves-light btn blue" onclick='atras()'><i class="material-icons left">arrow_back</i>ATRAS</a>
     &nbsp;&nbsp;
    <span class="card-title" style="font-size: 24px;color: #3293a2;margin-left: 63%" ><b>{{ name|upper }} CAJAS</b></span>
</div>


<div class='card'>
    <div class='card-content'>

<div class='row'>
  <form onsubmit="guardarMantenimiento(this,{% if request.GET.id %}{{request.GET.id }}{% else %}''{% endif %},'cajas','admn_caja' );return false;"
  >
    {% csrf_token %}
    <div class='col s4'></div>
    <div class='col s4'>
      <div class='input-field'>
        {{ form.descripcion }}
        <label for="id_descripcion" class="active">DESCRIPCION</label>
      </div>
      <div class='input-field'>
        {{ form.montoingresos }}
        <label for="id_montoingresos" class="active">MONTO INGRESO</label>
      </div>
      <div class='input-field'>
        {{ form.montoegresos }}
        <label for="id_montoegresos" class="active">MONTO EGRESO</label>
      </div>
      <div class='input-field'>
        {{ form.montototal }}
        <label for="id_montototal" class="active">MONTO TOTAL</label>
      </div>
    </div>
    <div class='col s12' align='center'>
      <button type='submit' class='waves-effect waves-light btn' id="btn_envio">
        <i class='material-icons left'>send</i>{{ name }}
      </button>
    </div>
  </form>
</div>

    </div>
</div>
<!-- Modal -->
<div id='myModal'> </div>

apps/admn_caja/templates/cajas/list_cajas.html
<div class="card-panel">
    <a class="waves-effect waves-light btn blue" onclick='atras()'><i class="material-icons left">arrow_back</i>ATRAS</a>
     &nbsp;&nbsp;
    <span class="card-title" style="font-size: 24px;color: #3293a2;margin-left: 25%" ><b>LISTA DE CAJAS</b></span>
    <a href='#admn_caja/cajas/add?id=' class="waves-effect waves-light btn green"  style="float: right;"><i class="material-icons left">add</i>AGREGAR</a>
</div>

<div class='card'>
  <div class='card-content'>
    <table>
      <thead>
        <tr>
          <td>#</td>
          <td>descripcion</td>
          <td>montoingresos</td>
          <td>montoegresos</td>
          <td>montototal</td>
          <td>Editar</td>
          <td>Eliminar</td>
        </tr>
      </thead>
    <tbody>
      {% for foo in object_list %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>{{ foo.descripcion}}</td>
          <td>{{ foo.montoingresos}}</td>
          <td>{{ foo.montoegresos}}</td>
          <td>{{ foo.montototal}}</td>
          <td>
            <a style='color: red' href='#admn_caja/cajas/update/{{ foo.id}}/?id={{ foo.id}}'>
              <i class='fa fa-pencil-square-o'></i>
          </a>
          </td>
          <td>
            <a style='color: red'  onclick="deleteMantenimiento('admn_caja','cajas',{{ foo.id}})" style='cursor: pointer'>
              <i class='fa fa-trash puntero'></i>
            </a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
</div>
<!--div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
    <a class="btn-floating btn-large red" href='#admn_caja/cajas/add?id='>
        <i class="large material-icons">add</i>
    </a>
</div-->
<script>
$('table').dataTable(datEs);
</script>

apps/admn_caja/templates/cajas/sesiones.html
<div class="card-panel">
    <a class="waves-effect waves-light btn blue" onclick='atras()'><i class="material-icons left">arrow_back</i>ATRAS</a>
     &nbsp;&nbsp;
    <span class="card-title" style="font-size: 24px;color: #3293a2;margin-left: 20%;margin-right: 15%" ><b>LISTA DE SESIONES CAJA</b></span>
    {% if caja_estado == 'false' %}
        <a class="waves-effect waves-light btn green" onclick='open_caja()'><i class="material-icons left">lock_open</i>APERTURAR CAJA</a>
    {% else %}
        <a class="waves-effect waves-light btn red" onclick='cerrar_caja()'><i class="material-icons left">lock_outline</i>CERRAR CAJA</a>
    {% endif %}

</div>

<div class='card'>
  <div class='card-content'>
    <table>
      <thead>
        <tr>
          <td>#</td>
          <td>Caja</td>
          <td>Fecha</td>
          <td>Monto Apertura</td>
          <td>Monto Cierre</td>
          <td>Estado</td>
        </tr>
      </thead>
    <tbody>
      {% for f in listasesiones %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>{{ f.idcaja_id}}</td>
          <td>{{ f.fecha}}</td>
          <td>{{ f.montoapertura}}</td>
          <td>{{ f.montocierre}}</td>
          <td >
            {% if f.status == False %}
                <div align="center">
                    <a  class="waves-effect waves-light btn red ">Cerrada</a>
                </div>
            {% else %}
                <div align="center">
                    <a class="waves-effect waves-light btn green">Aperturada</a>
                </div>
            {% endif %}
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
</div>
<!-- Lista Cajas -->
<style>
    #modalcaja_12{
        width: 30%;
        height: 250px;
    }
    .title{
        font-size: 16px;
        color:#fff;
        font-weight: bold;
        background: #FEBBB7 !important;
        width: 100%;
        padding: 5px;
        text-align: center;
    }
</style>
<div id="modalcaja_12" class="modal modal-fixed-footer">
    <div class="modal-content">
        <h4>Seleccione la Caja que va aperturar</h4>
        <div class="title">Seleccione La Caja</div>
        <select id="caja" name="caja">
            <option value="">Seleccione</option>
            {% for f in listacajas %}
                <option value="{{ f.id }}">{{ f.descripcion }} - Saldo Actual: {{ f.montototal }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="modal-footer">
        <a class=" modal-action waves-effect waves-danger btn-flat" onclick="cerrar_modal()">
            CANCELAR
        </a>
        <a class=" modal-action waves-effect waves-green btn-flat" onclick='aperturar_caja()'>
            <i class="material-icons left">lock_open</i>APERTURAR CAJA
        </a>
    </div>
</div>

{% load static %}

<script>
    function open_caja() {
        $("#modalcaja_12").openModal();
    }

    function cerrar_modal() {
        $("#modalcaja_12").closeModal();
    }

    function aperturar_caja(){
        if($("#caja").val()==""){
            $(".title").show();return 0;
        }
        l = Lobibox.confirm({
            msg : "¿Está seguro Aperturar Caja Ahora: ?",
            callback: function ($this, type, ev) {
                if(type=="yes"){
                    $.get("admn_caja/sesion_caja/aperturar",{'caja':$("#caja").val()},function(data){
                        traemedatos("admn_caja/sesion_caja/listar");
                        noti('success', "Caja Aperturada Correctamente");
                        $("#modalcaja_12").closeModal();
                    });
                }
            }
        });
    }

    function cerrar_caja(){
        l = Lobibox.confirm({
            msg : "¿Está seguro Cerrar Caja Ahora: ?",
            callback: function ($this, type, ev) {
                if(type=="yes"){
                    $.get("admn_caja/sesion_caja/cerrar",{},function(data){
                        traemedatos("admn_caja/sesion_caja/listar");
                        noti('success', "Caja Cerrada Correctamente");
                    });
                }
            }
        });
    }
</script>
<script>
$('table').dataTable(datEs);
$('select').material_select();
</script>