apps/compra/urls.py
from django.conf.urls import url 
#views.
from .views.v_compra import list_compra, add_compra, update_compra, delete_compra,infoproducto,guardar_detalle, ver_detalle
from .views.v_proveedor import list_proveedor, add_proveedor, update_proveedor, delete_proveedor

urlpatterns = [
    # compra
    url(r'^compra/compra/listar/$', list_compra.as_view()),
    url(r'^compra/compra/add/$', add_compra.as_view()),
    url(r'^compra/compra/update/(?P<pk>\d+)/$', update_compra.as_view()),
    url(r'^compra/compra/delete/(?P<id>\d+)/$', delete_compra),
    url(r'^compra/compra/infoproducto/$',infoproducto),
    url(r'^compra/compra/guardardetalle/$',guardar_detalle),
    url(r'^compra/compra/verdetalle/$',ver_detalle),

    #proveedor
    url(r'^compra/proveedor/listar/$', list_proveedor.as_view()),
    url(r'^compra/proveedor/add/$', add_proveedor.as_view()),
    url(r'^compra/proveedor/update/(?P<pk>\d+)/$', update_proveedor.as_view()),
    url(r'^compra/proveedor/delete/(?P<id>\d+)/$', delete_proveedor)
]

config/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.security.urls')),
    url(r'^', include('apps.admn_caja.urls')),
  url(r'^', include('apps.reportes.urls')),
  url(r'^', include('apps.servicio.urls')),
  url(r'^', include('apps.compra.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/compra/models.py
from django.db import models
from apps.core.core import TimeStampedModel
from apps.servicio.models import productos
from apps.admn_caja.models import movimiento

class proveedor(TimeStampedModel):
    razon_social=models.CharField(max_length=100,blank=True,null=True)
    direcion=models.CharField(max_length=100,blank=True,null=True)
    celular=models.CharField(max_length=10,blank=True,null=True)
    ruc=models.CharField(max_length=11,blank=True,null=True)
    def __str__(self):
        return self.razon_social

class compra(TimeStampedModel):
    nombreproveedor=models.ForeignKey(proveedor,blank=True,null=True)
    descripcion= models.CharField(max_length=100)
    fechacompra=models.DateField()
    totalcompra=models.DecimalField(decimal_places=2, max_digits=6)
    totaligv=models.DecimalField(decimal_places=2, max_digits=6)

    def __str__(self):
        return self.descripcion

    def l_compra(self):
        return compra.objects.filter(status=True)

class cuotascompra(TimeStampedModel):
    nrocuota=models.IntegerField()
    montocuota=models.DecimalField(decimal_places=2, max_digits=6)
    montocancelado=models.DecimalField(decimal_places=2, max_digits=6)
    fechavencimiento=models.DateField()
    fechacanselado=models.DateField()
    idcompra=models.ForeignKey(compra)

class detalle_amortizacion(TimeStampedModel):
    monto=models.DecimalField(decimal_places=2, max_digits=6)
    idmovimiento=models.ForeignKey(movimiento)
    idcuota=models.ForeignKey(cuotascompra)

class detalle_compra_producto(TimeStampedModel):

    cantidad=models.IntegerField()
    precio=models.DecimalField(decimal_places=2, max_digits=6)
    ivg=models.DecimalField(decimal_places=2, max_digits=6)
    idcompra=models.ForeignKey(compra)
    idproducto=models.ForeignKey(productos)

apps/compra/forms/f_compra.py
from django import forms
from ..models import compra

class compraForm(forms.ModelForm):
  class Meta():
    model = compra
    fields = '__all__'
    widgets = {
      'fechacompra': forms.DateInput(attrs={'class': 'datepicker'})
    }
    exclude = ('status','created_at', 'updated_at', 'deleted_at')

apps/compra/forms/f_proveedor.py
from django import forms
from ..models import proveedor

class proveedorForm(forms.ModelForm):
  class Meta():
    model = proveedor
    fields = '__all__'
    exclude = ('status', 'created_at', 'updated_at', 'deleted_at')

apps/compra/views/v_compra.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import HttpResponse
from apps.core.crud import ListBase, SaveBase, UpdateBase
from ..models import compra, proveedor, detalle_compra_producto
from ...servicio.models import productos
from ..forms.f_compra import compraForm
from django.core.serializers.json import DjangoJSONEncoder
from decimal import Decimal
import json

class list_compra(ListBase):
  template_name = 'compras/list_compra.html'
  queryset = compra.objects.filter(status=True)
#  print(queryset.query)

class add_compra(SaveBase):
  form_class = compraForm
  template_name = 'compras/frm_compra.html'

  def get_context_data(self, **kwargs):
       context = super(add_compra, self).get_context_data(**kwargs)
     #  context['producto'] =[{'descripcion': '---------'}]
       context['producto'] = productos.objects.filter(status=True).values('id','descripcion')
    #   print(context['producto'])
       return context

class update_compra(UpdateBase):
  form_class = compraForm
  template_name = 'compras/frm_compra.html'
  model = compra

  def get_context_data(self, **kwargs):
    context = super(update_compra, self).get_context_data(**kwargs)
    context['producto'] = productos.objects.filter(status=True).values('id','descripcion')
    return context

@login_required(login_url='login/')
def delete_compra(em, id):
  #print(em)
  dp = compra.objects.get(pk=id)
  dp.status = False
  dp.save()
  return HttpResponse('DATOS ELIMINADOS')

@login_required(login_url='login/')
def infoproducto(request):
  data = productos.objects.filter(id=request.GET["idpro"]).values('precio')
  return HttpResponse(json.dumps(list(data),cls=DjangoJSONEncoder))

@login_required(login_url='login/')
def guardar_detalle(request):
  n_com = compra()
  n_com.descripcion = request.POST['descripcion']
  n_com.fechacompra = request.POST['fechacompra']
  n_com.totaligv = request.POST['totaligv']
  n_com.totalcompra = request.POST['totalcompra']
  n_com.nombreproveedor_id = request.POST['nombreproveedor']
  n_com.save()
  idc = compra.objects.latest('id')

  print(request.POST)
  re = {}
  for x,y,z,p in zip(request.POST.getlist('idproductitos[]'), request.POST.getlist('cantidades[]'), request.POST.getlist('precios[]'), request.POST.getlist('igvtotal[]')):
    re['idproducto_id'] = int(x)
    re['cantidad'] = int(y)
    re['precio'] = Decimal(z)
    re['ivg'] = Decimal(p)
    re['idcompra_id'] = idc.id
    detalle_compra_producto(**re).save()

  return HttpResponse('compra guardada')

@login_required(login_url='login/')
def ver_detalle(request):
  listacom = detalle_compra_producto.objects.filter(idcompra__fechacompra=request.GET["fecha"],idcompra=request.GET["id"], status=True).values\
    ('idcompra__nombreproveedor__razon_social','idcompra__descripcion','idcompra__fechacompra','idcompra__totalcompra'
     , 'idcompra__totaligv','idproducto__descripcion','cantidad','precio','ivg','status','idcompra')
  data = [
    {
      'detalle': list(listacom)
    }
  ]
  return HttpResponse(json.dumps(data,cls=DjangoJSONEncoder))

apps/compra/views/v_proveedor.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import HttpResponse
from apps.core.crud import ListBase, SaveBase, UpdateBase
from ..models import proveedor
from ...servicio.models import productos
from ..forms.f_proveedor import proveedorForm

class list_proveedor(ListBase):
  template_name = 'proveedor/list_proveedor.html'
  queryset = proveedor.objects.filter(status=True).values()
#  print(queryset.query)

class add_proveedor(SaveBase):
  form_class = proveedorForm
  template_name = 'proveedor/frm_proveedor.html'

class update_proveedor(UpdateBase):
  form_class = proveedorForm
  template_name = 'proveedor/frm_proveedor.html'
  model = proveedor

@login_required(login_url='login/')
def delete_proveedor(em, id):
  dp = proveedor.objects.get(pk=id)
  dp.status = False
  dp.save()
  return HttpResponse('DATOS ELIMINADOS')

apps/compra/templates/compras/frm_compra.html
<div class="card-panel">
    <a class="waves-effect waves-light btn blue" onclick='atras()'><i class="material-icons left">arrow_back</i>ATRAS</a>
     &nbsp;&nbsp;
    <span class="card-title" style="font-size: 24px;color: #3293a2;margin-left: 48%" ><b>{{ name|upper }} COMPRA</b></span>
</div>

<div class='card'>
    <div class='card-content'>

<div class='row'>
  <form id="form_compra" onsubmit="return guardarcomprita()">
    {% csrf_token %}

    <div class="row">

        <div class="input-field col s4">
            <div class='input-field'>
            {{ form.nombreproveedor}}
             <label for="select2-id_nombreproveerdor-container" class="active">PROVEEDOR</label>
            </div>
        </div>
        <div class='input-field col s4'>
            <div class='input-field'>
            {{ form.descripcion }}
             <label for="first_name" class="active">DESCRIPCION</label>
            </div>
        </div>
        <div class='input-field col s4'>
          <div class='input-field'>
            {{ form.fechacompra }}
           <label for="first_name" class="active">FECHA COMPRA</label>
          </div>
        </div>

    </div>
      <!-- lista de productos-->
      <center><h6>Lista de Productos</h6></center>
       <!-- lista de productos-->
      <div class="row producto">
          <div class="input-field col s3">
            <div class="input-field">
               <select class="producto" onchange="infoproducto()" id="producto" >
                 <option value="">----------</option>
                 {% for foo in producto %}
                  <option value="{{ foo.id}}">{{ foo.descripcion}}</option>
                 {% endfor %}
                </select>
               <label class="active">PRODUCTO</label>
            </div>
        </div>

        <div class='input-field col s2'>
          <div class='input-field'>
            <input type="number" id="precio" >
           <label for="first_name" class="active">PRECIO</label>
          </div>
        </div>
        <div class='input-field col s2'>
            <div class='input-field'>
             <input type="number" id="cantidad" >
             <label for="first_name" class="active">CANTIDAD</label>
            </div>
        </div>
        <div class='input-field col s2'>
          <div class='input-field'>
            <p>
              <input type="checkbox" class="filled-in" id="igvdetalle" checked="checked" />
              <label for="igvdetalle">IGV</label>
            </p>
          </div>
        </div>
        <div class='input-field col s2'>
          <div class='input-field'>
            <a class="waves-effect waves-light btn agregar" onclick="agregar()">AGREGAR</a>
          </div>
        </div>
    </div>


      <div class="row">
          <!-- tabla-->
           <div class='card'>
              <div class='card-content'>
                <table>
                  <thead>
                    <tr>
                <!--      <td>#</td> -->
                      <td>PRODUCTO</td>
                      <td>CANTIDAD</td>
                      <td>PRECIO</td>
                      <td>IGV</td>
                      <td>SUBTOTAL</td>
                      <td>MODIFICAR</td>
                      <td>QUITAR</td>
                    </tr>
                  </thead>
                <tbody id="conten">
                </tbody>
              </table>
            </div>
        </div>
      </div>
      <div class="row">
          <div class='input-field col s2'>
          <div class='input-field'>
            {{ form.totalcompra }}
           <label for="first_name" class="active">COMPRA TOTAL</label>
          </div>
        </div>
        <div class='input-field col s2'>
          <div class='input-field'>
            {{ form.totaligv }}
           <label for="first_name" class="active">TOTAL IGV</label>
          </div>
        </div>
      </div>
    <div class='col s12' align='center'>
      <button type='submit' class='waves-effect waves-light btn'>
        <i class='material-icons left'>send</i>{{ name }}
      </button>
    </div>
  </form>
</div>

    </div>
</div>
<!-- Modal -->
<div id='myModal'> </div>

<script>
$('.datepicker').pickadate({
    selectMonths: true, // Creates a dropdown to control month
    selectYears: true, // Creates a dropdown of 15 years to control year
    format: 'yyyy-mm-dd'
  });
    
    function infoproducto() {
        if($("#producto").val()!=""){
            $.getJSON("compra/compra/infoproducto",{'idpro':$("#producto").val()},function(data){
                $("#precio").val(data[0].precio);
            });
        }else{
            $("#precio").val("");
        }
    }
    var sumigv=0;
    var sumtotal=0;
    var canti=0;
    function agregar() {
        if($("#producto").val()=="" || $("#precio").val()=="" || $("#cantidad").val()==""){
            noti('error',"Debe completar todos los campos para agregar");
        }else{
          //  var canti = $("#conten tr").length;
           var product= $("#producto").val();
           var cantida=$("#cantidad").val();
           var preci=$("#precio").val();
             canti = canti +1;
            if( $('#igvdetalle').is(':checked') ) {
                var montoigv = 0.18*parseFloat($("#cantidad").val()*$("#precio").val());
                montoigv = montoigv.toFixed(2);
            }else{
                var montoigv = 0.00;
            }
           // var cars = [montoigv];
            var total = parseFloat($("#cantidad").val())*parseFloat($("#precio").val()) + parseFloat(montoigv);
            var idp = $("#producto").val();
            var html = "<tr id='producto_"+canti+"' class='pro_"+canti+"'>";
      //      html += "<td>"+canti+"</td>";
            html += "<td> <input type='hidden' name='idproductitos[]' value='"+$("#producto").val()+"'>"+$("#producto option:selected").text()+"</td>";
            html += "<td> <input type='hidden' name='cantidades[]' value='"+$("#cantidad").val()+"'>"+$("#cantidad").val()+"</td>";
            html += "<td> <input type='hidden' name='precios[]' value='"+$("#precio").val()+"'>"+$("#precio").val()+"</td>";
            html += "<td> <input type='hidden' name='igvtotal[]' value='"+montoigv+"'>"+montoigv+"</td>";
            sumigv=parseFloat(sumigv)+parseFloat(montoigv);
            html += "<td>"+total.toFixed(2)+"</td>";
            sumtotal=parseFloat(sumtotal)+parseFloat(total);
            html += "<td><i class='fa fa-pencil-square-o fa-2x' onclick='modificar("+canti+","+total+","+product+","+cantida+","+preci+","+sumigv+","+sumtotal+","+montoigv+")';></i></td>";
            html += "<td><i class='fa fa-times-circle fa-2x' onclick='quitar("+canti+","+total+","+product+","+cantida+","+preci+","+sumigv+","+sumtotal+","+montoigv+")';></i></td>";
            html += "</tr>";
       //     console.log(html);
            $("#id_totaligv").val(sumigv.toFixed(2));
            $("#id_totalcompra").val(sumtotal.toFixed(2));
            $("#conten").append(html);
            $("#producto").val("");$("#cantidad").val("");$("#precio").val("");
        }
    }
    var res=0;
    var resigv=0;
    function quitar(id,monto,pro,can,pre,tigv,toltal,igv) {

        resigv=parseFloat(sumigv.toFixed(2))-parseFloat(igv.toFixed(2));
       // alert(resigv.toFixed(2)+'='+parseFloat(sumigv.toFixed(2))+'-'+igv);
        sumigv=resigv;
       // alert(resigv+'='+sumigv);
       $("#id_totaligv").val(resigv.toFixed(2));
        res=parseFloat(sumtotal.toFixed(2))-(parseFloat(can)*parseFloat(pre) + parseFloat(igv)).toFixed(2);
      //  alert(res+'='+parseFloat(sumtotal.toFixed(2))+'-'+(parseFloat(can)*parseFloat(pre) + parseFloat(igv)).toFixed(2));
        sumtotal=res;
      //  alert(sumtotal.toFixed(2)+'='+res.toFixed(2))
       $("#id_totalcompra").val(res.toFixed(2));
       $('#producto_'+id).remove();

    }
    var resm=0;
    var resigvm=0;
    function modificar(id,monto,produ,canti,prec,toigv,tot,ig) {
      $("#producto").val(producto);
      $("#cantidad").val(cantidad);
      $("#precio").val(precio);
      resigvm=parseFloat(sumigv.toFixed(2))-parseFloat(ig.toFixed(2));
      sumigv=resigv;
      $("#id_totaligv").val(resigv.toFixed(2));
      resm=parseFloat(sumtotal.toFixed(2))-(parseFloat(canti)*parseFloat(prec) + parseFloat(ig)).toFixed(2);
      $("#id_totalcompra").val(resm.toFixed(2));
      $('#producto_'+id).remove();
    }

    function guardarcomprita() {
        var formData = $('#form_compra').serialize();
        $.ajax({
            url: "compra/compra/guardardetalle/",
            type: 'POST',
            data: formData,
            success: function(data){
                alert(data); return false;
            }
        });
        return false;
    }
</script>

<script>$('select').select2({width: '100%'});</script>

apps/compra/templates/compras/list_compra.html
<div class="card-panel">
    <a class="waves-effect waves-light btn blue" onclick='atras()'><i class="material-icons left">arrow_back</i>ATRAS</a>
     &nbsp;&nbsp;
    <span class="card-title" style="font-size: 24px;color: #3293a2;margin-left: 53%" ><b>LISTA DE COMPRA</b></span>
</div>
<!--h4 align='center' style='color: #3293a2'><b>LISTA DE TIPO_MOVIMIENTOS</b></h4>
<hr-->

<div class='card'>
  <div class='card-content'>
    <table>
      <thead>
        <tr>
          <td>#</td>
          <td>Nombre Proveedor</td>
          <td>Descripcion</td>
          <td>Fecha Compra</td>
          <td>Total Compra</td>
          <td>Total Igv</td>
          <td>Ver Compra</td>
        </tr>
      </thead>
    <tbody>
      {% for foo in object_list %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>{{ foo.nombreproveedor.razon_social}}</td>
          <td>{{ foo.descripcion}}</td>
          <td>{{ foo.fechacompra}}</td>
          <td>{{ foo.totalcompra}}</td>
          <td>{{ foo.totaligv}}</td>
          <td>
            <a style='color: red' onclick="modal1({{ foo.id}},'{{ foo.fechacompra|date:"Y-m-d"}}')">
              <i class='fa fa-eye '></i>
          </a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
  <div id="modal" class="modal">
    <div class="modal-content">
      <h4>DETALLE DE LA COMPRA</h4>
      <div class="row">
        <div id="contenido1"></div>
      </div>
    </div>
    <div class="modal-footer">
      <a class=" modal-action modal-close waves-effect waves-green btn-flat">CERRAR</a>
    </div>
  </div>
</div>

<div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
    <a class="btn-floating btn-large red" href='#compra/compra/add?id='>
        <i class="large material-icons">add</i>
    </a>
</div>


<script>
  $('table').dataTable(datEs);
  function modal1(idcomp,fechacomp) {
  $('#contenido1').empty();
    $.getJSON("compra/compra/verdetalle",{'id':idcomp,'fecha':fechacomp},function(data){
        var d=data[0].detalle;
        var h='';
        var cont=0;
              $.each(d,function (key,value) {

               console.log(value);
            //    console.log(value.detalle[key].idcompra__nombreproveedor__razon_social);
                if (cont==0){
                  h+="<div><div class='card-content'>" +
                    "<table><thead>" +
                    "<tr>" +
                    "<td>#</td><td>PRODUCTO</td><td>CANTIDAD</td><td>PRECIO</td><td>IGV</td><td>SUBTOTAL</td>" +
                    "</tr>" +
                    "</thead>" +
                    "<tbody id=tab'></tbody>" +
                    "</div></div>";
                  h+="<div class='input-field col s4'>" +
                    "<div class='input-field'>" +
                    "<input disabled type='text' id='cantidad' value='"+value.idcompra__nombreproveedor__razon_social+"'>" +
                    "<label for='first_name' class='active'>PROVEEDOR</label>" +
                    "</div></div>";
                  h+="<div class='input-field col s4'>" +
                    "<div class='input-field'>" +
                    "<input disabled type='text' id='cantidad' value='"+value.idcompra__descripcion+"'>" +
                    "<label for='first_name' class='active'>DESCRIPCION</label>" +
                    "</div></div>";
                  h+="<div class='input-field col s4'>" +
                    "<div class='input-field'>" +
                    "<input disabled type='text' id='cantidad' value='"+value.idcompra__fechacompra+"'>" +
                    "<label for='first_name' class='active'>FECHA COMPRA</label>" +
                    "</div></div>";
                  h+="<div class='input-field col s4'>" +
                    "<div class='input-field'>" +
                    "<input disabled type='number' id='cantidad' value='"+parseFloat(value.idcompra__totalcompra)+"'>" +
                    "<label for='first_name' class='active'>TOTAL COMPRA</label>" +
                    "</div></div>";
                  h+="<div class='input-field col s4'>" +
                    "<div class='input-field'>" +
                    "<input disabled type='number' id='cantidad' value='"+parseFloat(value.idcompra__totaligv)+"'>" +
                    "<label for='first_name' class='active'>TOTAL IGV</label>" +
                    "</div></div>";
                  cont++;
                }
                if (cont>0){
                    h += "<tr>";
                    h += "<td>"+(key+1)+"</td>";
                    h += "<td>"+value.idproducto__descripcion+"</td>";
                    h += "<td>"+value.cantidad+"</td>";
                    h += "<td>"+value.precio+"</td>";
                    h += "<td>"+value.ivg+"</td>";
                    h += "<td>"+(parseFloat(value.precio)*parseFloat(value.cantidad)+parseFloat(value.ivg))+"</td>";
                    h += "</tr>";
                }

               // console.log(a);
              });

             $('#contenido1').append(h);


     });
    $('#modal').openModal();

  }
</script>